quarkus.http.root-path=/api/v1
quarkus.http.port=18080
quarkus.jackson.fail-on-unknown-properties=false
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET
app.timezone=America/Lima

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:exchangedb;DB_CLOSE_DELAY=-1;MODE=LEGACY
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

quarkus.rest-client."com.abc.services.external.ExternalExchangeClient".url=https://free.e-api.net.pe
quarkus.rest-client."com.abc.services.external.ExternalExchangeClient".scope=singleton
